Do a recursive distclean in ncat before nbase. Otherwise, this sequence of commands 	./configure 	make 	make clean 	make distclean fails when makefile.dep is remade in the ncat directory: In file included from ncat.h:12,                  from ncat_main.c:4: ../nbase/nbase.h:128:26: error: nbase_config.h: No such file or directory (Many similar messages follow.)
This happened because "make clean" deletes ncat/makefile.dep. Remaking
makefile.dep requires preprocessing C files that indirectly include
nbase_config.h, which was removed from nbase by distclean. Doing the
distclean in ncat before nbase sidesteps the issue.


git-svn-id: svn://svn.insecure.org/nmap@13652 e0a8ed71-7df4-0310-8962-fdc924857419